//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        public int STT { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TinhTrangGiao { get; set; }
        public string DaThanhToan { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
    }
}
