//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang1
    {
        public int STT { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}
