//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaSP { get; set; }
        public string Hinh { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MoTa { get; set; }
        public string ChiTiet { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> MaHangSX { get; set; }
    }
}
