//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public int MaTK { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public Nullable<int> MaLoaiTK { get; set; }
        public string Hinh { get; set; }
        public string DiaChi { get; set; }
    }
}
